site_name: Data Warehouse 


repo_url: https://github.com/remitpro/data-warehouse-poc
repo_name: remitpro/data-warehouse-poc
edit_uri: edit/main/docs/

theme:
  name: material

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand


nav:
  - Introduction: index.md
  - Project Overview: overview.md
  - POC Overview: poc.md 
  - Benefits: benefits.md
  - Next Steps: next-steps.md



copyright: Copyright &copy; 2025  Remitpro 