dw_poc_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 
      port: 1433
      database: database
      schema: schema_name
      user: 
      password: 