data_warehouse_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: remitpro
      port: 1433
      database: remitpro
      schema: dev
      windows_login: True
      TrustServerCertificate: True


elementary:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: remitpro
      port: 1433
      database: remitpro
      schema: dev
      windows_login: True
      TrustServerCertificate: True